const LangDict = [
    {abbr: "af",name: "Afrikaans"},
    {abbr: "sq",name: "Albanian"},
    {abbr: "am",name: "Amharic"},
    {abbr: "ar",name: "Arabic"},
    {abbr: "hy",name: "Armenian"},
    {abbr: "as",name: "Assamese"},
    {abbr: "az",name: "Azerbaijani (Latin)"},
    {abbr: "bn",name: "Bangla"},
    {abbr: "ba",name: "Bashkir"},
    {abbr: "eu",name: "Basque"},
    {abbr: "bs",name: "Bosnian (Latin)"},
    {abbr: "bg",name: "Bulgarian"},
    {abbr: "yue",name: "Cantonese (Traditional)"},
    {abbr: "ca",name: "Catalan"},
    {abbr: "lzh",name: "Chinese (Literary)"},
    {abbr: "zh-Hans",name: "Chinese Simplified"},
    {abbr: "zh-Hant",name: "Chinese Traditional"},
    {abbr: "hr",name: "Croatian"},
    {abbr: "cs",name: "Czech"},
    {abbr: "da",name: "Danish"},
    {abbr: "prs",name: "Dari"},
    {abbr: "dv",name: "Divehi"},
    {abbr: "nl",name: "Dutch"},
    {abbr: "en",name: "English"},
    {abbr: "et",name: "Estonian"},
    {abbr: "fo",name: "Faroese"},
    {abbr: "fj",name: "Fijian"},
    {abbr: "fil",name: "Filipino"},
    {abbr: "fi",name: "Finnish"},
    {abbr: "fr",name: "French"},
    {abbr: "fr-ca",name: "French (Canada)"},
    {abbr: "gl",name: "Galician"},
    {abbr: "ka",name: "Georgian"},
    {abbr: "de",name: "German"},
    {abbr: "el",name: "Greek"},
    {abbr: "gu",name: "Gujarati"},
    {abbr: "ht",name: "Haitian Creole"},
    {abbr: "he",name: "Hebrew"},
    {abbr: "hi",name: "Hindi"},
    {abbr: "mww",name: "Hmong Daw (Latin)"},
    {abbr: "hu",name: "Hungarian"},
    {abbr: "is",name: "Icelandic"},
    {abbr: "id",name: "Indonesian"},
    {abbr: "ikt",name: "Inuinnaqtun"},
    {abbr: "iu",name: "Inuktitut"},
    {abbr: "iu-Latn",name: "Inuktitut (Latin)"},
    {abbr: "ga",name: "Irish"},
    {abbr: "it",name: "Italian"},
    {abbr: "ja",name: "Japanese"},
    {abbr: "kn",name: "Kannada"},
    {abbr: "kk",name: "Kazakh"},
    {abbr: "km",name: "Khmer"},
    {abbr: "tlh-Latn",name: "Klingon"},
    {abbr: "tlh-Piqd",name: "Klingon (plqaD)"},
    {abbr: "ko",name: "Korean"},
    {abbr: "ku",name: "Kurdish (Central)"},
    {abbr: "kmr",name: "Kurdish (Northern)"},
    {abbr: "ky",name: "Kyrgyz (Cyrillic)"},
    {abbr: "lo",name: "Lao"},
    {abbr: "lv",name: "Latvian"},
    {abbr: "lt",name: "Lithuanian"},
    {abbr: "mk",name: "Macedonian"},
    {abbr: "mg",name: "Malagasy"},
    {abbr: "ms",name: "Malay (Latin)"},
    {abbr: "ml",name: "Malayalam"},
    {abbr: "mt",name: "Maltese"},
    {abbr: "mi",name: "Maori"},
    {abbr: "mr",name: "Marathi"},
    {abbr: "mn-Cyrl",name: "Mongolian (Cyrillic)"},
    {abbr: "mn-Mong",name: "Mongolian (Traditional)"},
    {abbr: "my",name: "Myanmar"},
    {abbr: "ne",name: "Nepali"},
    {abbr: "nb",name: "Norwegian"},
    {abbr: "or",name: "Odia"},
    {abbr: "ps",name: "Pashto"},
    {abbr: "fa",name: "Persian"},
    {abbr: "pl",name: "Polish"},
    {abbr: "pt",name: "Portuguese (Brazil)"},
    {abbr: "pt-pt",name: "Portuguese (Portugal)"},
    {abbr: "pa",name: "Punjabi"},
    {abbr: "otq",name: "Queretaro Otomi"},
    {abbr: "ro",name: "Romanian"},
    {abbr: "ru",name: "Russian"},
    {abbr: "sm",name: "Samoan (Latin)"},
    {abbr: "sr-Cyrl",name: "Serbian (Cyrillic)"},
    {abbr: "sr-Latn",name: "Serbian (Latin)"},
    {abbr: "sk",name: "Slovak"},
    {abbr: "sl",name: "Slovenian"},
    {abbr: "so",name: "Somali (Arabic)"},
    {abbr: "es",name: "Spanish"},
    {abbr: "sw",name: "Swahili (Latin)"},
    {abbr: "sv",name: "Swedish"},
    {abbr: "ty",name: "Tahitian"},
    {abbr: "ta",name: "Tamil"},
    {abbr: "tt",name: "Tatar (Latin)"},
    {abbr: "te",name: "Telugu"},
    {abbr: "th",name: "Thai"},
    {abbr: "bo",name: "Tibetan"},
    {abbr: "ti",name: "Tigrinya"},
    {abbr: "to",name: "Tongan"},
    {abbr: "tr",name: "Turkish"},
    {abbr: "tk",name: "Turkmen (Latin)"},
    {abbr: "uk",name: "Ukrainian"},
    {abbr: "hsb",name: "Upper Sorbian"},
    {abbr: "ur",name: "Urdu"},
    {abbr: "ug",name: "Uyghur (Arabic)"},
    {abbr: "uz",name: "Uzbek (Latin"},
    {abbr: "vi",name: "Vietnamese"},
    {abbr: "cy",name: "Welsh"},
    {abbr: "yua",name: "Yucatec Maya"},
    {abbr: "zu",name: "Zulu"},
]

export default LangDict